# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  trackservice:
    image: trackservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "86:80"
    deploy:
      restart_policy:
        condition: always